/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Zygis
 */
public class GUI extends javax.swing.JFrame {

    private String lookUpList, matrixImage;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jButton_selImage = new javax.swing.JButton();
        jButton_selList = new javax.swing.JButton();
        jButton_Start = new javax.swing.JButton();
        jTextField_imagePath = new javax.swing.JTextField();
        jTextField_lookUpList = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_selImage.setText("Select Image");
        jButton_selImage.setToolTipText("");
        jButton_selImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selImageActionPerformed(evt);
            }
        });

        jButton_selList.setText("Select word list");
        jButton_selList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selListActionPerformed(evt);
            }
        });

        jButton_Start.setBackground(new java.awt.Color(0, 204, 0));
        jButton_Start.setText("Execute");
        jButton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartActionPerformed(evt);
            }
        });

        jTextField_imagePath.setEditable(false);
        jTextField_imagePath.setText("Select path to the image.");
        jTextField_imagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_imagePathActionPerformed(evt);
            }
        });

        jTextField_lookUpList.setEditable(false);
        jTextField_lookUpList.setText("Select path to the list with look up words.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_lookUpList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jTextField_imagePath, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_selImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_selList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_selImage)
                    .addComponent(jTextField_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_selList)
                    .addComponent(jTextField_lookUpList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Start, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This open dialog to select .txt file with words to find
     * @param evt 
     */
    private void jButton_selImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selImageActionPerformed
            final JFileChooser fc = new JFileChooser(new File(System.getProperty("user.dir")
                                                        +"\\resource")); 
            FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGE FILES", "jpg", "jpg");
            fc.setFileFilter(filter);
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                matrixImage = fc.getSelectedFile().toString();
                jTextField_imagePath.setText(matrixImage);                
                System.out.println("File path: " + matrixImage + ".");    
            } else {
                System.out.println(System.getProperty("user.dir")+"\\resource");
            }
            System.out.println(returnVal);
    }//GEN-LAST:event_jButton_selImageActionPerformed
/**
 * this opens dialog to select image on which you want to perform image procesing
 * @param evt 
 */
    private void jButton_selListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selListActionPerformed
        System.out.println(evt);  
        final JFileChooser fc = new JFileChooser(new File(System.getProperty("user.dir")
                + "\\resource"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            lookUpList = fc.getSelectedFile().toString();
            jTextField_lookUpList.setText(lookUpList);
            System.out.println("File path: " + lookUpList + ".");
        } else {
            System.out.println(System.getProperty("user.dir") + "\\resource");
        }
        System.out.println(returnVal);
    }//GEN-LAST:event_jButton_selListActionPerformed
/**
 * 
 * @param evt 
 * IGNORE ! (accidental function that I don't know how to delete on Netbeans)
 */
    private void jTextField_imagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_imagePathActionPerformed

    }//GEN-LAST:event_jTextField_imagePathActionPerformed
/**
 * this fires up the AppMain class and analise the aplication
 * @param evt 
 */
    private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartActionPerformed
        try {
            AppMain.main(this.matrixImage, this.lookUpList);
            JFrame showImage = new JFrame() ;
            showImage.setSize(640, 640);
            showImage.setVisible(true);
                JLabel imageCotainer = new JLabel(new ImageIcon(System.getProperty("user.dir") + 
                                                    "\\resource"+"\\output.jpeg"));
            JScrollPane jsp = new JScrollPane(imageCotainer);
            showImage.add(jsp);
            
        } catch (IOException ex) {
            System.out.println("shit happened");
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Start;
    private javax.swing.JButton jButton_selImage;
    private javax.swing.JButton jButton_selList;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JTextField jTextField_imagePath;
    private javax.swing.JTextField jTextField_lookUpList;
    // End of variables declaration//GEN-END:variables
}
